[project]
name = "proyecto1sd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.114.1",
    "motor==3.5.1",
    "boto3 == 1.35.47"
]
